name: CI
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Vuepress-Deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.GIT_TOKEN }}
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: npm install && npm run build
          BUILD_DIR: public
  sync:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: 'git@github.com:kvery/kvery.github.io.git'
          destination-repo: 'git@gitee.com:kvery/kvery.git'
  reload-pages:
    needs: sync
    runs-on: ubuntu-latest
    steps:
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: kvery
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: kvery/kvery
          branch: gh-pages
